version: "3.3"
services:
  jenkins:
    image: jenkins-docker
    build:
      context: pipeline
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - testnet
   
#  ubuntu_01:
#    image: custom-ubuntu
#    build:
#      context: Ubuntu
#    container_name: ubuntu_01
#    restart: always
#    volumes:
#      - $PWD/ubuntu_home01:/tmp/ubuntu_home
#    networks:
#      - testnet

#  ubuntu_02:
#    depends_on:
#      - ubuntu_01
#    image: custom-ubuntu
#    build:
#      context: Ubuntu
#    container_name: ubuntu_02
#    volumes:
#      - $PWD/ubuntu_home02:/tmp/ubuntu_home
#    networks:
#      - testnet          

networks:
  testnet:
